import java.io.*;

/**
 * Class used to manage the process of creating tests results
 */
public class ResultGenerator {
    /**
     * Static method that checks in database which tests where chosen and then writing
     * results generated by created Compound objects based on accordingly man or woman standards.
     *
     * @throws IOException appearing due to file opening error
     */
    public static void Generate() throws IOException {
        File database = new File("..\\pjava-2022z-projekt\\Databases\\database.med");
        File standards_man = new File("..\\pjava-2022z-projekt\\standards_man.txt");
        File standards_woman = new File("..\\pjava-2022z-projekt\\standards_woman.txt");
        File standardFile = standards_man;
        BufferedReader readDatabase = new BufferedReader(new FileReader(database));

        String data;
        while (true) {
            data = readDatabase.readLine();
            if (data.contains("Kobieta"))
                standardFile = standards_woman;

            if (data.contains("/")) {
                readDatabase.close();
                BufferedWriter writeResults = new BufferedWriter(new FileWriter(database, true));
                writeResults.write("\n");
                String[] processedData = data.split("/");
                for (String analysis : processedData) {
                    BufferedReader readStandards = new BufferedReader(new FileReader(standardFile));
                    while (true) {
                        String standard = readStandards.readLine();
                        if (standard == null)
                            break;
                        if (standard.contains(analysis)) {
                            String[] parameters = standard.split(" ");
                            Compound c = new Compound(parameters[0], parameters[1], parameters[2]);
                            writeResults.write(c + "\n");
                        }
                    }
                    readStandards.close();
                }
                writeResults.close();
                break;
            }
        }
    }
}
